# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'init script' # runs during prebuild
    command: echo 'start script'

image: gitpod/workspace-dotnet

vscode:
  extensions:
    - muhammad-sammy.csharp