name: codacy-coverage-reporter

on: ["push"]

jobs:
  codacy-coverage-reporter:
    runs-on: ubuntu-latest
    name: codacy-coverage-reporter
    steps:
      - uses: actions/checkout@master
      - name : coverlet
        uses: b3b00/coverlet-action@1.3.4
        with:
          testProject: 'Tests/Tests.csproj'
          output: 'opencover.xml'
          outputFormat: 'opencover'
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{secrets.CODACY_PROJECT_TOKEN}}
          coverage-reports: ${{steps.coverlet.outputs.coverageFile}}
