name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
#    - name: SonarScanner for .NET 5 with pull request decoration support
#      uses: highbyte/sonarscan-dotnet@2.0
#      with:
#        sonarProjectKey: archanox_RGBDS2CIL
#        sonarProjectName:  RGBDS2CIL
#        sonarOrganization: archanox
#      env:
#        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: CodeCov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: dotnet-tests-report
      uses: zyborg/dotnet-tests-report@v1.3.0
      with:          
        report_name: tests
        report_title: Tests
        github_token: ${{ secrets.GITHUB_TOKEN }}
        gist_name: test_results.md
        gist_badge_label: '%Counters_passed%/%Counters_total%'
        gist_token: ${{ secrets.GIST_TOKEN }}
        uses: actions/checkout@master
    
