name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: dotnet-tests-report
      uses: zyborg/dotnet-tests-report@v1.3.0
      with:          
        report_name: tests
        report_title: Tests
        github_token: ${{ secrets.GITHUB_TOKEN }}
        gist_name: test_results.md
        gist_badge_label: '%Counters_passed%/%Counters_total%'
        gist_token: ${{ secrets.GIST_TOKEN }}
