jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: dotnet-tests-report
        uses: zyborg/dotnet-tests-report@v1.3.0
        with:
          report_name: tests
          report_title: Tests
          github_token: ${{ secrets.GITHUB_TOKEN }}
