name: xUnit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: dotnet-tests-report
        uses: zyborg/dotnet-tests-report@v1.3.0
        with:
          project_path: Tests
          report_name: tests
          report_title: Tests
          github_token: ${{ secrets.GITHUB_TOKEN }}
